# Generated by Django 5.1.4 on 2025-01-16 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comment_post_like_post_alter_input_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 17, 0, 16, 15, 658150)),
        ),
    ]
