# Generated by Django 5.1.4 on 2025-01-22 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_input_post_like_alter_input_post_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment_post',
        ),
        migrations.DeleteModel(
            name='like_post',
        ),
        migrations.AlterField(
            model_name='input_post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 22, 13, 53, 7, 786320)),
        ),
    ]
