# Generated by Django 5.1.4 on 2025-01-22 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_comment_post_delete_like_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 22, 14, 35, 58, 519112)),
        ),
    ]
