# Generated by Django 5.1.4 on 2025-01-22 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_input_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 22, 14, 36, 20, 450172)),
        ),
    ]
