# Generated by Django 5.1.4 on 2025-01-23 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_input_post_user_comment_input_post_user_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 23, 14, 36, 9, 21469)),
        ),
    ]
