# Generated by Django 5.1.4 on 2025-01-24 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_input_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 24, 15, 10, 38, 408255)),
        ),
    ]
